import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import { Welcome } from '../components/Welcome';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';

export default function Home() {
	const queryClient = new QueryClient();

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={styles.main}>
				<QueryClientProvider client={queryClient}>
					<h1>Hi</h1>
				</QueryClientProvider>
			</main>
		</>
	);
}
